version: '2'
services:
  gpmaster:
     image: 10.0.0.96:5000/database/gp_43:v1 
     hostname: master
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=102
     networks: 
       - docker_gwbridge
     ports:
       - "20010:2345"
     volumes:
       - /opt/gpmaster/gpdata_43:/home/gpadmin/gpdata
       - /opt/gpmaster/conf_43:/home/gpadmin/conf
     privileged: true
     tty: true
  gpnode1:
     image: 10.0.0.96:5000/database/gp_43:v1
     hostname: sdw1
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - "20011:40000"
       - "20012:40001"
       - "20013:43000"
       - "20014:43001"
     volumes:
       - /opt/gpnode1/gpadta_43:/home/gpadmin/gpdata
     privileged: true
     tty: true
  gpnode2:
     image: 10.0.0.96:5000/database/gp_43:v1
     hostname: sdw2
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=106
     networks: 
       - docker_gwbridge
     ports:
       - "20015:40000"
       - "20016:40001"
       - "20017:43000"
       - "20018:43001"
     volumes:
       - /opt/gpnode2/gpdata_43:/home/gpadmin/gpdata
     privileged: true
     tty: true

