version: '2'
services:
  gpmaster:
     image: 10.0.0.96:5000/database/centos_gp:latest
     hostname: master
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=102
     networks: 
       - docker_gwbridge
     ports:
       - "11000:5432"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
     privileged: true
     tty: true
  gpnode1:
     image: 10.0.0.96:5000/database/centos_gp:latest
     hostname: sdw1
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - "11001:5432"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
     privileged: true
     tty: true
  gpnode2:
     image: 10.0.0.96:5000/database/centos_gp:latest
     hostname: sdw2
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=110
     networks: 
       - docker_gwbridge
     ports:
       - "11002:5432"
     volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup
     privileged: true
     tty: true

